"""Generate the browser-side RotaCare Q&A fallback from the canonical HTML."""

from __future__ import annotations

import json
from pathlib import Path

from qa_service import load_entries


OUTPUT_PATH = Path(__file__).with_name("rotacare_qa_data.js")


def build() -> Path:
    translations = json.loads(
        Path(__file__).with_name("translations.json").read_text(encoding="utf-8")
    )
    entries = [
        {
            "number": entry.number,
            "section": entry.section,
            "question": entry.question,
            "answer": entry.answer,
            "followUp": entry.follow_up or None,
            "sourceNote": entry.source_note or None,
            "answerZh": translations[str(entry.number)]["zh"],
            "answerEs": translations[str(entry.number)]["es"],
        }
        for entry in load_entries(Path(__file__).with_name("RotaCare_San_Jose_Complete_QA.html"))
    ]
    payload = json.dumps(entries, ensure_ascii=False, separators=(",", ":"))
    OUTPUT_PATH.write_text(
        "// Generated by build_browser_data.py; do not edit manually.\n"
        f"window.ROTACARE_QA={payload};\n",
        encoding="utf-8",
    )
    return OUTPUT_PATH


if __name__ == "__main__":
    print(build())
